# Generated by Django 4.0.6 on 2022-07-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('unid', models.CharField(default=0, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('phone', models.BigIntegerField(default=0)),
                ('gender', models.CharField(default='', max_length=10)),
                ('father', models.CharField(default='', max_length=40)),
                ('mother', models.CharField(default='', max_length=40)),
                ('address', models.CharField(default='', max_length=100)),
                ('group', models.CharField(default='', max_length=5)),
                ('age', models.IntegerField(default=0)),
                ('dob', models.CharField(default='', max_length=12)),
                ('speechTherapy', models.IntegerField(default=0)),
                ('therapy', models.IntegerField(default=0)),
                ('transportation', models.IntegerField(default=0)),
                ('admissionCharge', models.IntegerField(default=0)),
                ('monthlyCharge', models.IntegerField(default=0)),
                ('snacks', models.IntegerField(default=0)),
                ('isAdmission', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('studentunid', models.CharField(default=0, max_length=50)),
                ('transactionunid', models.CharField(default=0, max_length=50, primary_key=True, serialize=False)),
                ('date', models.CharField(default='', max_length=15)),
                ('paidAmount', models.IntegerField(default=0)),
                ('forMonth', models.CharField(max_length=20)),
                ('speechTherapy', models.IntegerField(default=0)),
                ('therapy', models.IntegerField(default=0)),
                ('transportation', models.IntegerField(default=0)),
                ('admissionCharge', models.IntegerField(default=0)),
                ('monthlyCharge', models.IntegerField(default=0)),
                ('snacks', models.IntegerField(default=0)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
