# Generated by Django 4.0.6 on 2022-07-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='title',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='admissionCharge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='dob',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='father',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='group',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='monthlyCharge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='mother',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='snacks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='speechTherapy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='therapy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='transportation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='unid',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
