# Generated by Django 4.0.6 on 2022-07-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_remove_studentmodel_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='unid',
            field=models.CharField(default=0, max_length=50, primary_key=True, serialize=False),
        ),
    ]
