# Generated by Django 4.0.6 on 2022-07-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_remove_studentmodel_id_alter_studentmodel_unid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('studentunid', models.CharField(default=0, max_length=50, primary_key=True, serialize=False)),
                ('date', models.CharField(default='', max_length=12)),
                ('paidAmount', models.IntegerField(default=0)),
                ('forMonth', models.CharField(max_length=20)),
                ('speechTherapy', models.IntegerField(default=0)),
                ('therapy', models.IntegerField(default=0)),
                ('transportation', models.IntegerField(default=0)),
                ('admissionCharge', models.IntegerField(default=0)),
                ('monthlyCharge', models.IntegerField(default=0)),
                ('snacks', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='isAdmission',
            field=models.BooleanField(default=False),
        ),
    ]
